/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_ca_project_redgroup;

import java.util.ArrayList;

/**
 *
 * @author lucasandrade
 */
public class RedGroup_LandingPageGUI extends javax.swing.JFrame {

    /**
     * Creates new form RedGroup_LandingPageGUI
     */
    public RedGroup_LandingPageGUI() {
        initComponents();
    }
    private int userId;

    public RedGroup_LandingPageGUI(int userId) {
    this.userId = userId;
    initComponents();
    displayUserData(); // Show user-specific data
}

    private void displayUserData() {
    HealthDataDB db = new HealthDataDB();
    db.getConnection();
    ArrayList<HealthRecord> userRecords = db.getHealthDataByUser(userId);
    // Display user records in the GUI
    db.closeConnection();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLandingPage = new javax.swing.JLabel();
        Section1_landingPageButton = new javax.swing.JButton();
        Section2_landingPageButton = new javax.swing.JButton();
        Section3_landingPageButton = new javax.swing.JButton();
        dailyTips_landingPageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLandingPage.setText("Red Group - Health App - Landing Page");

        Section1_landingPageButton.setText("User Setttings");
        Section1_landingPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Section1_landingPageButtonActionPerformed(evt);
            }
        });

        Section2_landingPageButton.setText("Health Overview");
        Section2_landingPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Section2_landingPageButtonActionPerformed(evt);
            }
        });

        Section3_landingPageButton.setText("My Reports");
        Section3_landingPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Section3_landingPageButtonActionPerformed(evt);
            }
        });

        dailyTips_landingPageButton.setText("My Health Recommendation");
        dailyTips_landingPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyTips_landingPageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dailyTips_landingPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Section1_landingPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLandingPage)
                    .addComponent(Section2_landingPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Section3_landingPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(titleLandingPage)
                .addGap(56, 56, 56)
                .addComponent(Section1_landingPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Section2_landingPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Section3_landingPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dailyTips_landingPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Section1_landingPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Section1_landingPageButtonActionPerformed
        new Section1Frame().setVisible(true); 
        this.dispose(); 
    }//GEN-LAST:event_Section1_landingPageButtonActionPerformed

    private void Section2_landingPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Section2_landingPageButtonActionPerformed
    new Section2Frame(userId).setVisible(true);
    this.dispose(); 
     }//GEN-LAST:event_Section2_landingPageButtonActionPerformed

    private void Section3_landingPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Section3_landingPageButtonActionPerformed
        new Section3Frame().setVisible(true); 
        this.dispose(); 
    }//GEN-LAST:event_Section3_landingPageButtonActionPerformed

    private void dailyTips_landingPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyTips_landingPageButtonActionPerformed
 
    new HealthRecommendations().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_dailyTips_landingPageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedGroup_LandingPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedGroup_LandingPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedGroup_LandingPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedGroup_LandingPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RedGroup_LoginPageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Section1_landingPageButton;
    private javax.swing.JButton Section2_landingPageButton;
    private javax.swing.JButton Section3_landingPageButton;
    private javax.swing.JButton dailyTips_landingPageButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titleLandingPage;
    // End of variables declaration//GEN-END:variables
}
