/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_ca_project_redgroup;

import javax.swing.JOptionPane;


/**
 *
 * @author lucasandrade
 */
public class Section1Frame extends javax.swing.JFrame {

    /**
     * Creates new form Section1Frame
     */

    
    private void initializeUserProfile() {
    HealthDataDB db = new HealthDataDB();
    db.getConnection();
    UserProfile profile = db.getUserProfile();
    db.closeConnection();

    if (profile != null) {
        name_Section1Input.setText(profile.getName());
        age_Section1Input.setText(String.valueOf(profile.getAge()));
        weight_Section1Input.setText(String.valueOf(profile.getWeight()));
        height_Section1Input.setText(String.valueOf(profile.getHeight()));
        activityLevel_Section1Selector.setSelectedItem(profile.getActivityLevel());
        goal_Section1Selector.setSelectedItem(profile.getGoal());
        
        // Update BMI details after loading profile data
        updateBMIDetails();
    }
}
        public Section1Frame() {
    initComponents();
    initializeUserProfile(); // Load user data into the form
    
    // placeholders
        addPlaceholder(name_Section1Input, "Enter name");
        addPlaceholder(age_Section1Input, "Enter age");
        addPlaceholder(weight_Section1Input, "(e.g., 70.5)");
        addPlaceholder(height_Section1Input, "(e.g., 175.0)");
        
        // update bmi when weight or height changes
    weight_Section1Input.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusLost(java.awt.event.FocusEvent e) {
            updateBMIDetails();
        }
    });

    height_Section1Input.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusLost(java.awt.event.FocusEvent e) {
            updateBMIDetails();
        }
    });
        
}
        // Override the setVisible method
            @Override
            public void setVisible(boolean visible) {
                if (visible) {
                    initializeUserProfile(); // Reload user profile data when the form is open
                }
        super.setVisible(visible);
}

        
        
        // placeholder method
    private void addPlaceholder(javax.swing.JTextField field, String placeholder) {
        field.setText(placeholder);
        field.setForeground(java.awt.Color.GRAY);

        field.addFocusListener(new java.awt.event.FocusListener() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(java.awt.Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (field.getText().isEmpty()) {
                    field.setForeground(java.awt.Color.GRAY);
                    field.setText(placeholder);
                }
            }
        });
        
    }

        private void updateBMIDetails() {
            try {
                // Create a temporary UserProfile instance with current form data
                double weight = Double.parseDouble(weight_Section1Input.getText());
                double height = Double.parseDouble(height_Section1Input.getText());

        UserProfile tempProfile = new UserProfile(
            0, //  ID
            "", // not needed 
            0, // not needed 
            weight,
            height,
            "", // not needed
            ""  // not needed
        );

        // Calculate and display bmi and classification
        double bmi = tempProfile.calculateBMI();
        if (bmi != -1) {
            bmiTextField.setText(String.format("%.2f", bmi));
            classificationTextField.setText(tempProfile.getBMIClassification());
            recommendedTextField.setText("18.5 - 24.9"); // Example range
            targetTextField.setText("22.0"); // Example target
        } else {
            bmiTextField.setText("N/A");
            classificationTextField.setText("Invalid input");
            recommendedTextField.setText("");
            targetTextField.setText("");
        }
    } catch (NumberFormatException e) {
        // invalid inputs 
        bmiTextField.setText("N/A");
        classificationTextField.setText("Invalid input");
        recommendedTextField.setText("");
        targetTextField.setText("");
        System.err.println("Error updating BMI details: " + e.getMessage());
    }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name_Section1Label = new javax.swing.JLabel();
        age_Section1Label = new javax.swing.JLabel();
        weight_Section1Label = new javax.swing.JLabel();
        height_Section1Label = new javax.swing.JLabel();
        activityLevel_Section1Label = new javax.swing.JLabel();
        goal_Section1Label = new javax.swing.JLabel();
        updateButton_Section1 = new javax.swing.JButton();
        name_Section1Input = new javax.swing.JTextField();
        age_Section1Input = new javax.swing.JTextField();
        weight_Section1Input = new javax.swing.JTextField();
        height_Section1Input = new javax.swing.JTextField();
        homeButtonSection1 = new javax.swing.JButton();
        activityLevel_Section1Selector = new javax.swing.JComboBox<>();
        goal_Section1Selector = new javax.swing.JComboBox<>();
        bmiLabel = new javax.swing.JLabel();
        classificationLabel = new javax.swing.JLabel();
        recommendedLabel = new javax.swing.JLabel();
        targetLabel = new javax.swing.JLabel();
        bmiTextField = new javax.swing.JLabel();
        classificationTextField = new javax.swing.JLabel();
        recommendedTextField = new javax.swing.JLabel();
        targetTextField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("User Profile:");

        name_Section1Label.setText("Name:");

        age_Section1Label.setText("Age:");

        weight_Section1Label.setText("Weight:");

        height_Section1Label.setText("Height:");

        activityLevel_Section1Label.setText("Activity Level:");

        goal_Section1Label.setText("Goals:");

        updateButton_Section1.setText("Update Details");
        updateButton_Section1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButton_Section1ActionPerformed(evt);
            }
        });

        homeButtonSection1.setText("Home");
        homeButtonSection1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonSection1ActionPerformed(evt);
            }
        });

        activityLevel_Section1Selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select activity level", "Sedentary", "Lightly Active", "Moderately Active", "Very Active", "Extra Active" }));
        activityLevel_Section1Selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activityLevel_Section1SelectorActionPerformed(evt);
            }
        });

        goal_Section1Selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a goal", "Weight Loss", "Muscle Gain", "Improved Health" }));
        goal_Section1Selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goal_Section1SelectorActionPerformed(evt);
            }
        });

        bmiLabel.setText("BMI:");

        classificationLabel.setText("Classification:");

        recommendedLabel.setText("Recommended Rage:");

        targetLabel.setText("Ideal BMI target:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(age_Section1Label)
                            .addComponent(name_Section1Label)
                            .addComponent(weight_Section1Label)
                            .addComponent(height_Section1Label)
                            .addComponent(activityLevel_Section1Label)
                            .addComponent(goal_Section1Label))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(goal_Section1Selector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(activityLevel_Section1Selector, javax.swing.GroupLayout.Alignment.LEADING, 0, 162, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(weight_Section1Input, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(height_Section1Input, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(age_Section1Input, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(name_Section1Input, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(classificationLabel)
                                    .addComponent(bmiLabel)
                                    .addComponent(targetLabel))
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(recommendedLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(updateButton_Section1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeButtonSection1)
                    .addComponent(bmiTextField)
                    .addComponent(classificationTextField)
                    .addComponent(recommendedTextField)
                    .addComponent(targetTextField))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name_Section1Label)
                            .addComponent(name_Section1Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(age_Section1Label)
                            .addComponent(age_Section1Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(weight_Section1Label)
                            .addComponent(weight_Section1Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(height_Section1Label)
                            .addComponent(height_Section1Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(activityLevel_Section1Label)
                            .addComponent(activityLevel_Section1Selector, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bmiLabel)
                            .addComponent(bmiTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(classificationLabel)
                            .addComponent(classificationTextField))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recommendedLabel)
                            .addComponent(recommendedTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(targetLabel)
                            .addComponent(targetTextField))
                        .addGap(20, 20, 20)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goal_Section1Label)
                    .addComponent(goal_Section1Selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton_Section1)
                    .addComponent(homeButtonSection1))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonSection1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonSection1ActionPerformed
        saveUserProfile(); // Save silently
    new RedGroup_LandingPageGUI().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_homeButtonSection1ActionPerformed

    private void updateButton_Section1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButton_Section1ActionPerformed
     try {
        // Save the user profile to the database
        saveUserProfile();

        // Show success message
        JOptionPane.showMessageDialog(this, "Details updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Optionally reload the profile (if necessary)
        // initializeUserProfile();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "An error occurred while updating details: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_updateButton_Section1ActionPerformed

    private void activityLevel_Section1SelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activityLevel_Section1SelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activityLevel_Section1SelectorActionPerformed

    private void goal_Section1SelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goal_Section1SelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goal_Section1SelectorActionPerformed

    private void saveUserProfile() {
        try {
        // new UserProfile object 
        UserProfile updatedProfile = new UserProfile(
            1, // if the user ID is 1
            name_Section1Input.getText(),
            Integer.parseInt(age_Section1Input.getText()),
            Double.parseDouble(weight_Section1Input.getText()),
            Double.parseDouble(height_Section1Input.getText()),
            activityLevel_Section1Selector.getSelectedItem().toString(),
            goal_Section1Selector.getSelectedItem().toString()
        );

        // Save or update the user profile in the DB
        HealthDataDB db = new HealthDataDB();
        db.getConnection();
        db.saveOrUpdateUserProfile(updatedProfile); // Save to the DB
        db.closeConnection();

        // Log success
        System.out.println("Data saved successfully for user: " + updatedProfile.getName());
    } catch (NumberFormatException e) {
        System.err.println("Invalid input format: " + e.getMessage());
    } catch (Exception e) {
        System.err.println("Error saving user profile: " + e.getMessage());
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Section1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Section1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Section1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Section1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Section1Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activityLevel_Section1Label;
    private javax.swing.JComboBox<String> activityLevel_Section1Selector;
    private javax.swing.JTextField age_Section1Input;
    private javax.swing.JLabel age_Section1Label;
    private javax.swing.JLabel bmiLabel;
    private javax.swing.JLabel bmiTextField;
    private javax.swing.JLabel classificationLabel;
    private javax.swing.JLabel classificationTextField;
    private javax.swing.JLabel goal_Section1Label;
    private javax.swing.JComboBox<String> goal_Section1Selector;
    private javax.swing.JTextField height_Section1Input;
    private javax.swing.JLabel height_Section1Label;
    private javax.swing.JButton homeButtonSection1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name_Section1Input;
    private javax.swing.JLabel name_Section1Label;
    private javax.swing.JLabel recommendedLabel;
    private javax.swing.JLabel recommendedTextField;
    private javax.swing.JLabel targetLabel;
    private javax.swing.JLabel targetTextField;
    private javax.swing.JButton updateButton_Section1;
    private javax.swing.JTextField weight_Section1Input;
    private javax.swing.JLabel weight_Section1Label;
    // End of variables declaration//GEN-END:variables
}
